"""
Pydantic schemas for Skill Definitions.

Skills are the "executable context" of the Company Brain. They define
step-by-step operational procedures that the WorkflowAgent can execute.

These schemas ensure that any skill generated by the LLM is strictly
typed and validated before being stored in the database or executed.
"""

from typing import Any
from pydantic import BaseModel, Field, field_validator


class SkillStep(BaseModel):
    """A single step within a skill execution."""
    step_number: int = Field(..., ge=1, description="Sequential order of the step")
    action_name: str = Field(..., min_length=1, description="Name of the action executor to call (e.g., 'stripe_refund')")
    description: str = Field(..., description="Human-readable description of what this step does")
    required_inputs: list[str] = Field(default_factory=list, description="Keys expected in the trigger data or context")
    execution_conditions: list[str] = Field(default_factory=list, description="Logic conditions that must be true to execute this step")
    requires_human_approval: bool = Field(default=False, description="If true, CriticAgent must pause and escalate this specific step")
    escalate_on_failure: bool = Field(default=True, description="If true, failure of this step halts the workflow and escalates")


class SkillDefinition(BaseModel):
    """The complete definition of an executable skill."""
    schema_version: str = Field(default="1.0")
    name: str = Field(..., min_length=3, max_length=120)
    description: str = Field(..., description="High-level description of when and why this skill is used")
    
    # Triggers tell the WorkflowAgent when this skill is applicable
    trigger_keywords: list[str] = Field(default_factory=list, description="Keywords that suggest this skill is relevant")
    trigger_conditions: list[str] = Field(default_factory=list, description="Conditions required for this skill to apply (e.g., 'data.topic == refund')")
    
    # The actual execution flow
    steps: list[SkillStep] = Field(..., min_length=1)
    
    # Safety guardrails that the CriticAgent enforces globally for this skill
    guardrails: list[str] = Field(default_factory=list, description="Absolute invariant rules (e.g., 'Never refund over $1000')")

    @field_validator("steps")
    @classmethod
    def validate_step_ordering(cls, steps: list[SkillStep]) -> list[SkillStep]:
        """Ensure steps are ordered sequentially starting from 1."""
        sorted_steps = sorted(steps, key=lambda s: s.step_number)
        for i, step in enumerate(sorted_steps):
            if step.step_number != i + 1:
                raise ValueError(f"Step numbers must be sequential. Found step {step.step_number} at index {i}")
        return sorted_steps


class SkillGenerateRequest(BaseModel):
    """Internal request schema for synthesizing a new skill from a document cluster."""
    cluster_id: str
    document_contents: list[str]
    tenant_id: str


class SkillGenerateResponse(BaseModel):
    """Output from the LLM synthesis pipeline."""
    definition: SkillDefinition
    confidence_score: float = Field(..., ge=0.0, le=1.0)
    risk_level: str = Field(..., pattern="^(low|medium|high)$")
    reasoning: str = Field(..., description="LLM's justification for synthesizing this skill")
